name: "encoded_id"

services:
  encoded-id-dev-env:
    container_name: encoded-id-dev-env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000"
    volumes:
      - vscode-home:/home/vscode

volumes:
  vscode-home: